on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch:

jobs:
    build:
        name: "Build packages"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
            - name: "Setup python"
              uses: "actions/setup-python@v5"
              with:
                  python-version: "3.11"
            - name: "Setup poetry"
              uses: "Gr1N/setup-poetry@v8"
            - name: "Install depends"
              run: "poetry install"
            - name: "Build wheel"
              run: "poetry build"
            - name: "Create release"
              uses: "softprops/action-gh-release@v1"
              with:
                  files: "dist/*"
                  generate_release_notes: true
